/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailSentRouteImport } from './routes/verify-email-sent'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTokensRouteImport } from './routes/_auth/tokens'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthAwaitingApprovalRouteImport } from './routes/_auth/awaiting-approval'
import { Route as AuthSettingsRouteRouteImport } from './routes/_auth/settings/route'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthAppsIndexRouteImport } from './routes/_auth/apps/index'
import { Route as AuthUsersListRouteImport } from './routes/_auth/users/list'
import { Route as AuthUsersApprovalsRouteImport } from './routes/_auth/users/approvals'
import { Route as AuthSettingsStorageRouteImport } from './routes/_auth/settings/storage'
import { Route as AuthSettingsRegistrationRouteImport } from './routes/_auth/settings/registration'
import { Route as AuthSettingsAuthenticationRouteImport } from './routes/_auth/settings/authentication'
import { Route as AuthSettingsMailRouteRouteImport } from './routes/_auth/settings/mail/route'
import { Route as AuthAppsSlugRouteRouteImport } from './routes/_auth/apps/$slug/route'
import { Route as AuthSettingsMailIndexRouteImport } from './routes/_auth/settings/mail/index'
import { Route as AuthAppsSlugIndexRouteImport } from './routes/_auth/apps/$slug/index'
import { Route as AuthSettingsMailTemplatesRouteImport } from './routes/_auth/settings/mail/templates'
import { Route as AuthSettingsMailLogsRouteImport } from './routes/_auth/settings/mail/logs'
import { Route as AuthAppsSlugChannelsRouteImport } from './routes/_auth/apps/$slug/channels'
import { Route as AuthAppsSlugReleasesIndexRouteImport } from './routes/_auth/apps/$slug/releases/index'
import { Route as AuthAppsSlugReleasesVersionRouteImport } from './routes/_auth/apps/$slug/releases/$version'

const VerifyEmailSentRoute = VerifyEmailSentRouteImport.update({
  id: '/verify-email-sent',
  path: '/verify-email-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTokensRoute = AuthTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAwaitingApprovalRoute = AuthAwaitingApprovalRouteImport.update({
  id: '/awaiting-approval',
  path: '/awaiting-approval',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRouteRoute = AuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthAppsIndexRoute = AuthAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUsersListRoute = AuthUsersListRouteImport.update({
  id: '/users/list',
  path: '/users/list',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUsersApprovalsRoute = AuthUsersApprovalsRouteImport.update({
  id: '/users/approvals',
  path: '/users/approvals',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsStorageRoute = AuthSettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsRegistrationRoute =
  AuthSettingsRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsAuthenticationRoute =
  AuthSettingsAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsMailRouteRoute = AuthSettingsMailRouteRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthAppsSlugRouteRoute = AuthAppsSlugRouteRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsMailIndexRoute = AuthSettingsMailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsMailRouteRoute,
} as any)
const AuthAppsSlugIndexRoute = AuthAppsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppsSlugRouteRoute,
} as any)
const AuthSettingsMailTemplatesRoute =
  AuthSettingsMailTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthSettingsMailRouteRoute,
  } as any)
const AuthSettingsMailLogsRoute = AuthSettingsMailLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthSettingsMailRouteRoute,
} as any)
const AuthAppsSlugChannelsRoute = AuthAppsSlugChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthAppsSlugRouteRoute,
} as any)
const AuthAppsSlugReleasesIndexRoute =
  AuthAppsSlugReleasesIndexRouteImport.update({
    id: '/releases/',
    path: '/releases/',
    getParentRoute: () => AuthAppsSlugRouteRoute,
  } as any)
const AuthAppsSlugReleasesVersionRoute =
  AuthAppsSlugReleasesVersionRouteImport.update({
    id: '/releases/$version',
    path: '/releases/$version',
    getParentRoute: () => AuthAppsSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/device': typeof DeviceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/awaiting-approval': typeof AuthAwaitingApprovalRoute
  '/profile': typeof AuthProfileRoute
  '/tokens': typeof AuthTokensRoute
  '/apps/$slug': typeof AuthAppsSlugRouteRouteWithChildren
  '/settings/mail': typeof AuthSettingsMailRouteRouteWithChildren
  '/settings/authentication': typeof AuthSettingsAuthenticationRoute
  '/settings/registration': typeof AuthSettingsRegistrationRoute
  '/settings/storage': typeof AuthSettingsStorageRoute
  '/users/approvals': typeof AuthUsersApprovalsRoute
  '/users/list': typeof AuthUsersListRoute
  '/apps/': typeof AuthAppsIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/apps/$slug/channels': typeof AuthAppsSlugChannelsRoute
  '/settings/mail/logs': typeof AuthSettingsMailLogsRoute
  '/settings/mail/templates': typeof AuthSettingsMailTemplatesRoute
  '/apps/$slug/': typeof AuthAppsSlugIndexRoute
  '/settings/mail/': typeof AuthSettingsMailIndexRoute
  '/apps/$slug/releases/$version': typeof AuthAppsSlugReleasesVersionRoute
  '/apps/$slug/releases/': typeof AuthAppsSlugReleasesIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/device': typeof DeviceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/awaiting-approval': typeof AuthAwaitingApprovalRoute
  '/profile': typeof AuthProfileRoute
  '/tokens': typeof AuthTokensRoute
  '/': typeof AuthIndexRoute
  '/settings/authentication': typeof AuthSettingsAuthenticationRoute
  '/settings/registration': typeof AuthSettingsRegistrationRoute
  '/settings/storage': typeof AuthSettingsStorageRoute
  '/users/approvals': typeof AuthUsersApprovalsRoute
  '/users/list': typeof AuthUsersListRoute
  '/apps': typeof AuthAppsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/apps/$slug/channels': typeof AuthAppsSlugChannelsRoute
  '/settings/mail/logs': typeof AuthSettingsMailLogsRoute
  '/settings/mail/templates': typeof AuthSettingsMailTemplatesRoute
  '/apps/$slug': typeof AuthAppsSlugIndexRoute
  '/settings/mail': typeof AuthSettingsMailIndexRoute
  '/apps/$slug/releases/$version': typeof AuthAppsSlugReleasesVersionRoute
  '/apps/$slug/releases': typeof AuthAppsSlugReleasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/device': typeof DeviceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/_auth/awaiting-approval': typeof AuthAwaitingApprovalRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/tokens': typeof AuthTokensRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/apps/$slug': typeof AuthAppsSlugRouteRouteWithChildren
  '/_auth/settings/mail': typeof AuthSettingsMailRouteRouteWithChildren
  '/_auth/settings/authentication': typeof AuthSettingsAuthenticationRoute
  '/_auth/settings/registration': typeof AuthSettingsRegistrationRoute
  '/_auth/settings/storage': typeof AuthSettingsStorageRoute
  '/_auth/users/approvals': typeof AuthUsersApprovalsRoute
  '/_auth/users/list': typeof AuthUsersListRoute
  '/_auth/apps/': typeof AuthAppsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/apps/$slug/channels': typeof AuthAppsSlugChannelsRoute
  '/_auth/settings/mail/logs': typeof AuthSettingsMailLogsRoute
  '/_auth/settings/mail/templates': typeof AuthSettingsMailTemplatesRoute
  '/_auth/apps/$slug/': typeof AuthAppsSlugIndexRoute
  '/_auth/settings/mail/': typeof AuthSettingsMailIndexRoute
  '/_auth/apps/$slug/releases/$version': typeof AuthAppsSlugReleasesVersionRoute
  '/_auth/apps/$slug/releases/': typeof AuthAppsSlugReleasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/verify-email-sent'
    | '/settings'
    | '/awaiting-approval'
    | '/profile'
    | '/tokens'
    | '/apps/$slug'
    | '/settings/mail'
    | '/settings/authentication'
    | '/settings/registration'
    | '/settings/storage'
    | '/users/approvals'
    | '/users/list'
    | '/apps/'
    | '/settings/'
    | '/users/'
    | '/apps/$slug/channels'
    | '/settings/mail/logs'
    | '/settings/mail/templates'
    | '/apps/$slug/'
    | '/settings/mail/'
    | '/apps/$slug/releases/$version'
    | '/apps/$slug/releases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/verify-email-sent'
    | '/awaiting-approval'
    | '/profile'
    | '/tokens'
    | '/'
    | '/settings/authentication'
    | '/settings/registration'
    | '/settings/storage'
    | '/users/approvals'
    | '/users/list'
    | '/apps'
    | '/settings'
    | '/users'
    | '/apps/$slug/channels'
    | '/settings/mail/logs'
    | '/settings/mail/templates'
    | '/apps/$slug'
    | '/settings/mail'
    | '/apps/$slug/releases/$version'
    | '/apps/$slug/releases'
  id:
    | '__root__'
    | '/_auth'
    | '/accept-invite'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/verify-email-sent'
    | '/_auth/settings'
    | '/_auth/awaiting-approval'
    | '/_auth/profile'
    | '/_auth/tokens'
    | '/_auth/'
    | '/_auth/apps/$slug'
    | '/_auth/settings/mail'
    | '/_auth/settings/authentication'
    | '/_auth/settings/registration'
    | '/_auth/settings/storage'
    | '/_auth/users/approvals'
    | '/_auth/users/list'
    | '/_auth/apps/'
    | '/_auth/settings/'
    | '/_auth/users/'
    | '/_auth/apps/$slug/channels'
    | '/_auth/settings/mail/logs'
    | '/_auth/settings/mail/templates'
    | '/_auth/apps/$slug/'
    | '/_auth/settings/mail/'
    | '/_auth/apps/$slug/releases/$version'
    | '/_auth/apps/$slug/releases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  DeviceRoute: typeof DeviceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyEmailSentRoute: typeof VerifyEmailSentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email-sent': {
      id: '/verify-email-sent'
      path: '/verify-email-sent'
      fullPath: '/verify-email-sent'
      preLoaderRoute: typeof VerifyEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tokens': {
      id: '/_auth/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AuthTokensRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/awaiting-approval': {
      id: '/_auth/awaiting-approval'
      path: '/awaiting-approval'
      fullPath: '/awaiting-approval'
      preLoaderRoute: typeof AuthAwaitingApprovalRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/apps/': {
      id: '/_auth/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthAppsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/users/list': {
      id: '/_auth/users/list'
      path: '/users/list'
      fullPath: '/users/list'
      preLoaderRoute: typeof AuthUsersListRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/users/approvals': {
      id: '/_auth/users/approvals'
      path: '/users/approvals'
      fullPath: '/users/approvals'
      preLoaderRoute: typeof AuthUsersApprovalsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/storage': {
      id: '/_auth/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof AuthSettingsStorageRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/registration': {
      id: '/_auth/settings/registration'
      path: '/registration'
      fullPath: '/settings/registration'
      preLoaderRoute: typeof AuthSettingsRegistrationRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/authentication': {
      id: '/_auth/settings/authentication'
      path: '/authentication'
      fullPath: '/settings/authentication'
      preLoaderRoute: typeof AuthSettingsAuthenticationRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/mail': {
      id: '/_auth/settings/mail'
      path: '/mail'
      fullPath: '/settings/mail'
      preLoaderRoute: typeof AuthSettingsMailRouteRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/apps/$slug': {
      id: '/_auth/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AuthAppsSlugRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/mail/': {
      id: '/_auth/settings/mail/'
      path: '/'
      fullPath: '/settings/mail/'
      preLoaderRoute: typeof AuthSettingsMailIndexRouteImport
      parentRoute: typeof AuthSettingsMailRouteRoute
    }
    '/_auth/apps/$slug/': {
      id: '/_auth/apps/$slug/'
      path: '/'
      fullPath: '/apps/$slug/'
      preLoaderRoute: typeof AuthAppsSlugIndexRouteImport
      parentRoute: typeof AuthAppsSlugRouteRoute
    }
    '/_auth/settings/mail/templates': {
      id: '/_auth/settings/mail/templates'
      path: '/templates'
      fullPath: '/settings/mail/templates'
      preLoaderRoute: typeof AuthSettingsMailTemplatesRouteImport
      parentRoute: typeof AuthSettingsMailRouteRoute
    }
    '/_auth/settings/mail/logs': {
      id: '/_auth/settings/mail/logs'
      path: '/logs'
      fullPath: '/settings/mail/logs'
      preLoaderRoute: typeof AuthSettingsMailLogsRouteImport
      parentRoute: typeof AuthSettingsMailRouteRoute
    }
    '/_auth/apps/$slug/channels': {
      id: '/_auth/apps/$slug/channels'
      path: '/channels'
      fullPath: '/apps/$slug/channels'
      preLoaderRoute: typeof AuthAppsSlugChannelsRouteImport
      parentRoute: typeof AuthAppsSlugRouteRoute
    }
    '/_auth/apps/$slug/releases/': {
      id: '/_auth/apps/$slug/releases/'
      path: '/releases'
      fullPath: '/apps/$slug/releases/'
      preLoaderRoute: typeof AuthAppsSlugReleasesIndexRouteImport
      parentRoute: typeof AuthAppsSlugRouteRoute
    }
    '/_auth/apps/$slug/releases/$version': {
      id: '/_auth/apps/$slug/releases/$version'
      path: '/releases/$version'
      fullPath: '/apps/$slug/releases/$version'
      preLoaderRoute: typeof AuthAppsSlugReleasesVersionRouteImport
      parentRoute: typeof AuthAppsSlugRouteRoute
    }
  }
}

interface AuthSettingsMailRouteRouteChildren {
  AuthSettingsMailLogsRoute: typeof AuthSettingsMailLogsRoute
  AuthSettingsMailTemplatesRoute: typeof AuthSettingsMailTemplatesRoute
  AuthSettingsMailIndexRoute: typeof AuthSettingsMailIndexRoute
}

const AuthSettingsMailRouteRouteChildren: AuthSettingsMailRouteRouteChildren = {
  AuthSettingsMailLogsRoute: AuthSettingsMailLogsRoute,
  AuthSettingsMailTemplatesRoute: AuthSettingsMailTemplatesRoute,
  AuthSettingsMailIndexRoute: AuthSettingsMailIndexRoute,
}

const AuthSettingsMailRouteRouteWithChildren =
  AuthSettingsMailRouteRoute._addFileChildren(
    AuthSettingsMailRouteRouteChildren,
  )

interface AuthSettingsRouteRouteChildren {
  AuthSettingsMailRouteRoute: typeof AuthSettingsMailRouteRouteWithChildren
  AuthSettingsAuthenticationRoute: typeof AuthSettingsAuthenticationRoute
  AuthSettingsRegistrationRoute: typeof AuthSettingsRegistrationRoute
  AuthSettingsStorageRoute: typeof AuthSettingsStorageRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsMailRouteRoute: AuthSettingsMailRouteRouteWithChildren,
  AuthSettingsAuthenticationRoute: AuthSettingsAuthenticationRoute,
  AuthSettingsRegistrationRoute: AuthSettingsRegistrationRoute,
  AuthSettingsStorageRoute: AuthSettingsStorageRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthAppsSlugRouteRouteChildren {
  AuthAppsSlugChannelsRoute: typeof AuthAppsSlugChannelsRoute
  AuthAppsSlugIndexRoute: typeof AuthAppsSlugIndexRoute
  AuthAppsSlugReleasesVersionRoute: typeof AuthAppsSlugReleasesVersionRoute
  AuthAppsSlugReleasesIndexRoute: typeof AuthAppsSlugReleasesIndexRoute
}

const AuthAppsSlugRouteRouteChildren: AuthAppsSlugRouteRouteChildren = {
  AuthAppsSlugChannelsRoute: AuthAppsSlugChannelsRoute,
  AuthAppsSlugIndexRoute: AuthAppsSlugIndexRoute,
  AuthAppsSlugReleasesVersionRoute: AuthAppsSlugReleasesVersionRoute,
  AuthAppsSlugReleasesIndexRoute: AuthAppsSlugReleasesIndexRoute,
}

const AuthAppsSlugRouteRouteWithChildren =
  AuthAppsSlugRouteRoute._addFileChildren(AuthAppsSlugRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthAwaitingApprovalRoute: typeof AuthAwaitingApprovalRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthTokensRoute: typeof AuthTokensRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAppsSlugRouteRoute: typeof AuthAppsSlugRouteRouteWithChildren
  AuthUsersApprovalsRoute: typeof AuthUsersApprovalsRoute
  AuthUsersListRoute: typeof AuthUsersListRoute
  AuthAppsIndexRoute: typeof AuthAppsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthAwaitingApprovalRoute: AuthAwaitingApprovalRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthTokensRoute: AuthTokensRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAppsSlugRouteRoute: AuthAppsSlugRouteRouteWithChildren,
  AuthUsersApprovalsRoute: AuthUsersApprovalsRoute,
  AuthUsersListRoute: AuthUsersListRoute,
  AuthAppsIndexRoute: AuthAppsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  DeviceRoute: DeviceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyEmailSentRoute: VerifyEmailSentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
