/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/_demo/release-publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Stub for require_permission! tests. Removed by add-app-release-artifact when the real publish handler ships. */
    post: operations["release_publish"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/cli-token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["cli_token"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/setup/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["info"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_tokens"];
    put?: never;
    post: operations["create_token"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tokens/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["revoke_token"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["version"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Listed / detail representation of an `api_token` row. Never includes the
     *     plaintext token — that field exists only on [`CreateTokenResponse`] and
     *     [`CliTokenResponse`].
     */
    ApiToken: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at?: string | null;
      /** Format: uuid */
      id: string;
      kind: components["schemas"]["ApiTokenKind"];
      /** Format: date-time */
      last_used_at?: string | null;
      name: string;
      /** Format: uuid */
      owner_user_id: string;
      /** @description `None` for PAT (live from owner roles); `Some(subset)` for API Token. */
      permissions?: components["schemas"]["PermissionName"][] | null;
      /**
       * @description First 12 chars of the plaintext token, e.g. `swhv_pat_AbC`. Safe to
       *     display in lists to disambiguate tokens with similar names.
       */
      prefix: string;
      /** Format: date-time */
      revoked_at?: string | null;
    };
    /**
     * @description Wire kind discriminator. PAT inherits the owner's live permissions; API
     *     Token carries a snapshot subset chosen at create time.
     * @enum {string}
     */
    ApiTokenKind: "pat" | "api";
    CliTokenReq: {
      email: string;
      password: string;
      /** @description Friendly label surfaced in admin token lists, e.g. `"macbook-cli"`. */
      token_name: string;
    };
    /** @description Returned by `POST /api/v1/auth/cli-token`. Always `kind = pat`. */
    CliTokenResponse: {
      /** Format: date-time */
      created_at: string;
      kind: components["schemas"]["ApiTokenKind"];
      name: string;
      token: string;
    };
    CreateTokenRequest: {
      /** Format: date-time */
      expires_at?: string | null;
      kind: components["schemas"]["ApiTokenKind"];
      name: string;
      /**
       * @description Required when `kind = api` — must be a subset of the creator's current
       *     permissions. Must be `None` when `kind = pat` (server returns 422
       *     otherwise).
       */
      permissions?: components["schemas"]["PermissionName"][] | null;
    };
    /**
     * @description Returned exactly once by `POST /api/v1/tokens`. The plaintext `token` is
     *     the only opportunity to record it — server stores only the blake3 hash.
     */
    CreateTokenResponse: components["schemas"]["ApiToken"] & {
      /** @description Plaintext bearer token, format `swhv_(pat|api)_<43char base64url>`. */
      token: string;
    };
    HealthResponse: {
      /** @description `"connected"` when DB ping succeeds, `"unreachable"` otherwise. */
      db: string;
      /** @description `"ok"` when DB ping succeeds, `"degraded"` otherwise. */
      status: string;
    };
    LoginReq: {
      email: string;
      /**
       * @description Min 10 chars per `add-auth-and-rbac` proposal (server-side floor only;
       *     no upper bound — argon2 truncates internally if needed).
       */
      password: string;
    };
    MeResponse: {
      /** @description Sorted alphabetically by wire name for deterministic responses. */
      permissions: components["schemas"]["PermissionName"][];
      user: components["schemas"]["User"];
    };
    /**
     * @description Built-in permission strings per docs/13-rbac.md.
     *
     *     Wire format is the verb-scoped string (`"release:publish"`); the enum is
     *     the strongly-typed representation used in server middleware. New permissions
     *     are added by appending a new variant **and** an entry to [`PERMISSIONS`];
     *     `as_str` / `all` / `from_wire` derive from that single table.
     * @enum {string}
     */
    PermissionName:
      | "system:manage"
      | "user:manage"
      | "role:manage"
      | "token:manage"
      | "storage:manage"
      | "app:create"
      | "app:read"
      | "app:update"
      | "app:delete"
      | "release:create"
      | "release:read"
      | "release:update"
      | "release:publish"
      | "release:promote"
      | "release:rollback"
      | "release:yank"
      | "artifact:upload"
      | "artifact:read"
      | "artifact:delete"
      | "analytics:read"
      | "telemetry:read";
    /**
     * @description RFC 9457 problem+json body.
     *
     *     `pub` + `ToSchema` so OpenAPI can reference this as
     *     `#/components/schemas/Problem` from every error response.
     */
    Problem: {
      detail: string;
      /**
       * @description Populated only on `403 Forbidden`; names the permission the caller
       *     is missing (e.g. `"release:publish"`).
       */
      required_permission?: string | null;
      /** Format: int32 */
      status: number;
      title: string;
      /**
       * @description Stable error type URI; clients SHOULD branch on this rather than
       *     matching on `title` strings.
       * @example https://swarmhive.dev/errors/unauthorized
       */
      type: string;
    };
    SetupInfo: {
      /** @description `true` when the user table is empty and a setup-token POST is expected next. */
      setup_required: boolean;
    };
    SetupReq: {
      display_name: string;
      email: string;
      /** @description Owner account is privileged; bump the floor to 12 chars. */
      password: string;
      /**
       * @description One-shot bootstrap token printed to stdout on first run.
       *     32 random bytes → 43-char base64url-no-pad. Stricter
       *     `length(min=10)` is just a sanity floor.
       */
      token: string;
    };
    User: {
      avatar_url?: string | null;
      /** Format: date-time */
      created_at: string;
      display_name: string;
      email: string;
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      org_id: string;
      status: components["schemas"]["UserStatus"];
      /** Format: date-time */
      updated_at: string;
    };
    /** @enum {string} */
    UserStatus: "active" | "disabled" | "invited";
    VersionResponse: {
      /** @description Always `"swarmhive-server"`. */
      name: string;
      /** @description Server binary's `CARGO_PKG_VERSION` (matches the OpenAPI `info.version`). */
      version: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  release_publish: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authenticated caller has release:publish. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  cli_token: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CliTokenReq"];
      };
    };
    responses: {
      /** @description PAT minted. Plaintext returned exactly once. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CliTokenResponse"];
        };
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginReq"];
      };
    };
    responses: {
      /** @description Authenticated. Session cookie set. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user + permission set. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetupReq"];
      };
    };
    responses: {
      /** @description Owner created. Auto-logged in (session cookie set). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  info: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Whether first-run setup is still required. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetupInfo"];
        };
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_tokens: {
    parameters: {
      query?: {
        /**
         * @description Owner user id to filter on. Defaults to the authenticated user.
         *     Cross-user listing requires `token:manage`.
         */
        owner?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tokens owned by the target user. Plaintext never included. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiToken"][];
        };
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  create_token: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTokenRequest"];
      };
    };
    responses: {
      /** @description Token created. Plaintext returned exactly once. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateTokenResponse"];
        };
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  revoke_token: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Token id to revoke. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token revoked (or already revoked). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthenticated request, or invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Authenticated caller lacks the required permission. `required_permission` field names which. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict with current resource state (e.g. setup already complete). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Resource has been consumed or expired (e.g. setup token already used). */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request body failed validation (garde / serde). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Internal server error (database, config, or unexpected fault). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  version: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Binary build metadata. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server is up and DB ping succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Server is up but DB is unreachable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
